version: '3.9'
services:
  nova_dating_api:
    container_name: nova_dating_api
    image: node:18
    restart: always
    working_dir: /home/nova_dating/nova_dating_api
    volumes:
      - ./:/home/nova_dating/nova_dating_api
      - /home/nova_dating_files/api:/home/nova_dating_files/api
    command: bash -c "npm i && npm run build && npm run start-app"
    network_mode: "host"